### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by maxim133** [jnmaloney/WebGui#1]
Hello! Your code is doesn't work. There are errors "exception thrown: InternalError: too much recursion,resizeCanvas". Web console in Firefox shows message "too much recursion".
![изображение](https://user-images.githubusercontent.com/30491917/69013093-723f2100-098d-11ea-9d10-28ec2cfea748.png)
If I comment resizeCanvas(); in EM_JS, it works fine. Maybe fine. I'm not sure.

**Comment by jnmaloney** [comment]
Hi thanks for your comment.
I looked into the issue and I can't reproduce.
Could be a version issue with emcc or Firefox.
There is a pre-build page in the repository, does it give the same errror?

**Comment by maxim133** [comment]
Pre-build page works correctly. If rebuild, it was crashed.
I use Windows 10 with emcc 1.39.3 and Firefox 70.0.1 (64-bit).

**Comment by jnmaloney** [comment]
Ok I have emcc 1.37.36 and Firefox 70.0.1. I'll try updating and see what happens.

**Comment by jnmaloney** [comment]
After using emcc 1.39.3 I can reproduce the error on Ubuntu. Also I had to remove '-lGLU' from the make file. 

Thanks for letting me know.

**Comment by maxim133** [comment]
I also removed the flag '-lGLU'. I forgot to say about it.

**Comment by jnmaloney** [comment]
Ok I updated the source code.

The function that broke, is there to resize the window. So without it you only have a fixed size window. 

It seems the API got confused, so I just renamed the function.

**Comment by maxim133** [comment]
It's alive! Thank you.
