### ISSUE TITLE
js_resizeCanvas is not defined

### ISSUE THREAD

**Issue by samuel-watson** [jnmaloney/WebGui#12]
I'm not sure if this is an issue with the way I am trying to compile this repo or something else. I try to build the repo using emscripten with `emmake make` which completes without error. I have slightly edited the makefile to include the path to imgui and set the output to imgui.html. However when trying to launch the generated html, I get the js error `Uncaught ReferenceError: js_resizeCanvas is not defined`. The function in the output imgui.js just shows an Exit Status.

I can successfully launch the html and linked program in the repo, but I'm unable to build main.cpp from scratch. Am I missing something in the build process?

**Comment by jnmaloney** [comment]
I'm not using generated html in this project. 
I am compiling to wasm, (compiling to js should also work), and using a custom written html file, [imgui.html](https://github.com/jnmaloney/WebGui/blob/master/imgui.html).
The js_resizeCanvas function is defined in the javascript there.

**Comment by samuel-watson** [comment]
Thanks for the info - I had missed that you needed the shell file. It works now.
