### ISSUE TITLE
Can a license be added?

### ISSUE THREAD

**Issue by gallipolli** [jnmaloney/WebGui#8]
This is a great project! I would love to use it to experiment with building web-based workflows around the following tools for circuit board repairs:

https://github.com/inflex/OpenBoardData
https://github.com/OpenBoardView/OpenBoardView

Can a license be added to the WebGui project? Ideally, an MIT license would be great, since the projects I listed above are MIT licensed.
Thank you.

**Comment by jnmaloney** [comment]
I think because it follows https://github.com/ocornut/imgui that it can have MIT licence. 

With some changes I should be able to release the source as CC0 public domain.

**Comment by gallipolli** [comment]
Thank you, much appreciated!

**Comment by jnmaloney** [comment]
I have added the MIT license because there is still some code derived from [https://github.com/ocornut/imgui](https://github.com/ocornut/imgui)
